version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app.py:/app/app.py
      - ./Random_Forest.pkl:/app/Random_Forest.pkl
      - ./templates:/app/templates
      - ./nsl-kdd-data:/app/nsl-kdd-data
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: always

volumes:
  nsl-kdd-data: